server:
  port: 9001

spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27027,mongo3:27037/?replicaSet=rs0&retryWrites=true/structure_db
  application:
    name: STRUCTURE-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: eureka-0
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
